export interface RouteSeedEntry {
  id: string;
  origin: string;
  destination: string;
  distanceKm: number;
  company: string;
  departureTime: string;
  arrivalTime: string;
  duration: string;
  price: number;
  seatsAvailable: number;
  busType: string;
}

export const routeSeedData: RouteSeedEntry[] = [
  {
    id: 'HN-HCM-0600',
    origin: 'Hà Nội',
    destination: 'Hồ Chí Minh',
    distanceKm: 1730,
    company: 'Express Bus Lines',
    departureTime: '06:00',
    arrivalTime: '14:00',
    duration: '32h 00m',
    price: 1200000,
    seatsAvailable: 18,
    busType: 'Sleeper',
  },
  {
    id: 'HN-HCM-1800',
    origin: 'Hà Nội',
    destination: 'Hồ Chí Minh',
    distanceKm: 1730,
    company: 'Night Express',
    departureTime: '18:00',
    arrivalTime: '02:00',
    duration: '32h 00m',
    price: 1150000,
    seatsAvailable: 12,
    busType: 'VIP Sleeper',
  },
  {
    id: 'HN-DN-0700',
    origin: 'Hà Nội',
    destination: 'Đà Nẵng',
    distanceKm: 766,
    company: 'Golden Dragon',
    departureTime: '07:00',
    arrivalTime: '21:30',
    duration: '14h 30m',
    price: 650000,
    seatsAvailable: 22,
    busType: 'Premium',
  },
  {
    id: 'HN-DN-2000',
    origin: 'Hà Nội',
    destination: 'Đà Nẵng',
    distanceKm: 766,
    company: 'Vietnam Travel Bus',
    departureTime: '20:00',
    arrivalTime: '10:30',
    duration: '14h 30m',
    price: 620000,
    seatsAvailable: 16,
    busType: 'Sleeper',
  },
  {
    id: 'DN-HCM-0800',
    origin: 'Đà Nẵng',
    destination: 'Hồ Chí Minh',
    distanceKm: 961,
    company: 'Coastal Coach',
    departureTime: '08:00',
    arrivalTime: '23:30',
    duration: '15h 30m',
    price: 700000,
    seatsAvailable: 20,
    busType: 'Premium',
  },
  {
    id: 'HCM-KH-0900',
    origin: 'Hồ Chí Minh',
    destination: 'Khánh Hòa',
    distanceKm: 435,
    company: 'Luxury Coach',
    departureTime: '09:00',
    arrivalTime: '17:00',
    duration: '8h 00m',
    price: 430000,
    seatsAvailable: 14,
    busType: 'VIP Sleeper',
  },
  {
    id: 'HCM-LD-1000',
    origin: 'Hồ Chí Minh',
    destination: 'Lâm Đồng',
    distanceKm: 305,
    company: 'Green Highlands',
    departureTime: '10:00',
    arrivalTime: '17:30',
    duration: '7h 30m',
    price: 380000,
    seatsAvailable: 10,
    busType: 'Premium',
  },
  {
    id: 'HCM-CT-0630',
    origin: 'Hồ Chí Minh',
    destination: 'Cần Thơ',
    distanceKm: 169,
    company: 'Mekong Lines',
    departureTime: '06:30',
    arrivalTime: '10:30',
    duration: '4h 00m',
    price: 220000,
    seatsAvailable: 26,
    busType: 'Standard',
  },
  {
    id: 'HN-HP-0630',
    origin: 'Hà Nội',
    destination: 'Hải Phòng',
    distanceKm: 120,
    company: 'CityLink',
    departureTime: '06:30',
    arrivalTime: '09:30',
    duration: '3h 00m',
    price: 150000,
    seatsAvailable: 30,
    busType: 'Express',
  },
  {
    id: 'HN-LC-2100',
    origin: 'Hà Nội',
    destination: 'Lào Cai',
    distanceKm: 295,
    company: 'Mountain Rider',
    departureTime: '21:00',
    arrivalTime: '05:30',
    duration: '8h 30m',
    price: 420000,
    seatsAvailable: 19,
    busType: 'Sleeper',
  },
  {
    id: 'DN-HUE-1500',
    origin: 'Đà Nẵng',
    destination: 'Thừa Thiên Huế',
    distanceKm: 94,
    company: 'Heritage Shuttle',
    departureTime: '15:00',
    arrivalTime: '17:30',
    duration: '2h 30m',
    price: 160000,
    seatsAvailable: 24,
    busType: 'Standard',
  },
];
